-- English Space v10 — complete, rerunnable schema for student_id = 'amir'.
-- Run in Supabase Dashboard -> SQL Editor before opening the public site.

create extension if not exists pgcrypto;

create table if not exists public.homework_progress (
  id bigint generated by default as identity primary key,
  submission_id uuid not null default gen_random_uuid(),
  student_id text not null,
  student_name text,
  lesson_id text not null,
  lesson_title text,
  status text not null default 'draft',
  answers jsonb not null default '{}'::jsonb,
  score_correct integer,
  score_total integer,
  score_percent integer,
  checked_at timestamptz,
  submitted_at timestamptz,
  locked_at timestamptz,
  report_status text not null default 'not_sent',
  report_sent_at timestamptz,
  report_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.vocabulary_progress (
  id bigint generated by default as identity primary key,
  student_id text not null,
  word_key text not null,
  source_topic_id text,
  status text not null default 'new',
  learned_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.vocabulary_topic_progress (
  id bigint generated by default as identity primary key,
  student_id text not null,
  topic_id text not null,
  tests jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.grammar_progress (
  id bigint generated by default as identity primary key,
  student_id text not null,
  topic_id text not null,
  passed boolean not null default false,
  attempts integer not null default 0,
  best_score integer not null default 0,
  passed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.telegram_recipients (
  id bigint generated by default as identity primary key,
  student_id text not null,
  chat_id bigint not null,
  message_thread_id bigint,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.material_publications (
  id bigint generated by default as identity primary key,
  student_id text not null,
  material_type text not null,
  material_id text not null,
  notification_version integer not null default 1,
  status text not null default 'pending',
  payload jsonb not null default '{}'::jsonb,
  telegram_message_id bigint,
  error_message text,
  sent_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.homework_reports (
  id bigint generated by default as identity primary key,
  student_id text not null,
  lesson_id text not null,
  submission_id uuid not null,
  status text not null default 'pending',
  score_correct integer,
  score_total integer,
  score_percent integer,
  payload jsonb not null default '{}'::jsonb,
  telegram_message_id bigint,
  error_message text,
  sent_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Named constraints are recreated to keep reruns deterministic.
alter table public.homework_progress drop constraint if exists homework_progress_submission_id_key;
alter table public.homework_progress add constraint homework_progress_submission_id_key unique (submission_id);
alter table public.homework_progress drop constraint if exists homework_progress_student_lesson_key;
alter table public.homework_progress add constraint homework_progress_student_lesson_key unique (student_id, lesson_id);
alter table public.homework_progress drop constraint if exists homework_progress_status_check;
alter table public.homework_progress add constraint homework_progress_status_check check (status in ('draft','checked','submitted_pending_report','submitted'));
alter table public.homework_progress drop constraint if exists homework_progress_report_status_check;
alter table public.homework_progress add constraint homework_progress_report_status_check check (report_status in ('not_sent','pending','sent','failed'));
alter table public.homework_progress drop constraint if exists homework_progress_answers_object_check;
alter table public.homework_progress add constraint homework_progress_answers_object_check check (jsonb_typeof(answers) = 'object');
alter table public.homework_progress drop constraint if exists homework_progress_scores_check;
alter table public.homework_progress add constraint homework_progress_scores_check check (
  (score_correct is null and score_total is null and score_percent is null)
  or (
    score_correct is not null and score_total is not null and score_percent is not null
    and score_total >= 0 and score_correct between 0 and score_total and score_percent between 0 and 100
  )
);
alter table public.homework_progress drop constraint if exists homework_progress_final_dates_check;
alter table public.homework_progress add constraint homework_progress_final_dates_check check (
  status not in ('submitted_pending_report','submitted')
  or (submitted_at is not null and locked_at is not null)
);

alter table public.vocabulary_progress drop constraint if exists vocabulary_progress_student_word_key;
alter table public.vocabulary_progress add constraint vocabulary_progress_student_word_key unique (student_id, word_key);
alter table public.vocabulary_progress drop constraint if exists vocabulary_progress_status_check;
alter table public.vocabulary_progress add constraint vocabulary_progress_status_check check (status in ('new','known','difficult'));

alter table public.vocabulary_topic_progress drop constraint if exists vocabulary_topic_progress_student_topic_key;
alter table public.vocabulary_topic_progress add constraint vocabulary_topic_progress_student_topic_key unique (student_id, topic_id);
alter table public.vocabulary_topic_progress drop constraint if exists vocabulary_topic_progress_tests_array_check;
alter table public.vocabulary_topic_progress add constraint vocabulary_topic_progress_tests_array_check check (jsonb_typeof(tests) = 'array');

alter table public.grammar_progress drop constraint if exists grammar_progress_student_topic_key;
alter table public.grammar_progress add constraint grammar_progress_student_topic_key unique (student_id, topic_id);
alter table public.grammar_progress drop constraint if exists grammar_progress_values_check;
alter table public.grammar_progress add constraint grammar_progress_values_check check (attempts >= 0 and best_score between 0 and 100);

alter table public.telegram_recipients drop constraint if exists telegram_recipients_student_id_key;
alter table public.telegram_recipients add constraint telegram_recipients_student_id_key unique (student_id);
alter table public.telegram_recipients drop constraint if exists telegram_recipients_chat_id_key;
alter table public.telegram_recipients add constraint telegram_recipients_chat_id_key unique (chat_id);

alter table public.material_publications drop constraint if exists material_publications_dedupe_key;
alter table public.material_publications add constraint material_publications_dedupe_key unique (student_id, material_type, material_id, notification_version);
alter table public.material_publications drop constraint if exists material_publications_status_check;
alter table public.material_publications add constraint material_publications_status_check check (status in ('pending','sent','failed','skipped'));
alter table public.material_publications drop constraint if exists material_publications_version_check;
alter table public.material_publications add constraint material_publications_version_check check (notification_version > 0);
alter table public.material_publications drop constraint if exists material_publications_payload_object_check;
alter table public.material_publications add constraint material_publications_payload_object_check check (jsonb_typeof(payload) = 'object');

alter table public.homework_reports drop constraint if exists homework_reports_dedupe_key;
alter table public.homework_reports add constraint homework_reports_dedupe_key unique (student_id, lesson_id, submission_id);
alter table public.homework_reports drop constraint if exists homework_reports_status_check;
alter table public.homework_reports add constraint homework_reports_status_check check (status in ('pending','sent','failed'));
alter table public.homework_reports drop constraint if exists homework_reports_scores_check;
alter table public.homework_reports add constraint homework_reports_scores_check check (
  (score_correct is null and score_total is null and score_percent is null)
  or (score_correct is not null and score_total is not null and score_percent is not null
      and score_total >= 0 and score_correct between 0 and score_total and score_percent between 0 and 100)
);
alter table public.homework_reports drop constraint if exists homework_reports_payload_object_check;
alter table public.homework_reports add constraint homework_reports_payload_object_check check (jsonb_typeof(payload) = 'object');

create index if not exists homework_progress_student_updated_idx on public.homework_progress (student_id, updated_at desc);
create index if not exists vocabulary_progress_student_updated_idx on public.vocabulary_progress (student_id, updated_at desc);
create index if not exists grammar_progress_student_updated_idx on public.grammar_progress (student_id, updated_at desc);
create index if not exists material_publications_student_created_idx on public.material_publications (student_id, created_at desc);
create index if not exists homework_reports_student_created_idx on public.homework_reports (student_id, created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.protect_submitted_homework()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if current_user in ('anon', 'authenticated')
     and old.status in ('submitted_pending_report', 'submitted') then
    if new.student_id is distinct from old.student_id
       or new.student_name is distinct from old.student_name
       or new.lesson_id is distinct from old.lesson_id
       or new.lesson_title is distinct from old.lesson_title
       or new.submission_id is distinct from old.submission_id
       or new.status is distinct from old.status
       or new.answers is distinct from old.answers
       or new.score_correct is distinct from old.score_correct
       or new.score_total is distinct from old.score_total
       or new.score_percent is distinct from old.score_percent
       or new.checked_at is distinct from old.checked_at
       or new.submitted_at is distinct from old.submitted_at
       or new.locked_at is distinct from old.locked_at
       or new.created_at is distinct from old.created_at then
      raise exception 'Submitted homework is immutable for public clients' using errcode = '42501';
    end if;
  end if;
  return new;
end;
$$;

-- Atomic vocabulary-test application: all statuses and test history are committed together.
create or replace function public.apply_vocabulary_test(
  p_student_id text,
  p_topic_id text,
  p_outcomes jsonb,
  p_test jsonb
)
returns void
language plpgsql
security invoker
set search_path = public
as $$
declare
  item record;
  next_status text;
begin
  if p_student_id is null or p_topic_id is null or jsonb_typeof(p_outcomes) <> 'object' or jsonb_typeof(p_test) <> 'object' then
    raise exception 'Invalid vocabulary test payload';
  end if;

  for item in select key, value from jsonb_each_text(p_outcomes)
  loop
    next_status := item.value;
    if next_status not in ('known','difficult') then
      raise exception 'Invalid vocabulary status: %', next_status;
    end if;
    insert into public.vocabulary_progress (student_id, word_key, source_topic_id, status, learned_at)
    values (p_student_id, item.key, p_topic_id, next_status, case when next_status = 'known' then now() else null end)
    on conflict (student_id, word_key) do update
      set source_topic_id = excluded.source_topic_id,
          status = excluded.status,
          learned_at = case when excluded.status = 'known' then coalesce(public.vocabulary_progress.learned_at, now()) else null end,
          updated_at = now();
  end loop;

  insert into public.vocabulary_topic_progress (student_id, topic_id, tests)
  values (p_student_id, p_topic_id, jsonb_build_array(p_test))
  on conflict (student_id, topic_id) do update
    set tests = case
          when exists (
            select 1
            from jsonb_array_elements(public.vocabulary_topic_progress.tests) as existing(test)
            where existing.test = p_test
               or (p_test ? 'completedAt' and existing.test ->> 'completedAt' = p_test ->> 'completedAt')
          ) then public.vocabulary_topic_progress.tests
          else public.vocabulary_topic_progress.tests || jsonb_build_array(p_test)
        end,
        updated_at = now();
end;
$$;

-- Recreate updated_at triggers.
do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'homework_progress','vocabulary_progress','vocabulary_topic_progress','grammar_progress',
    'telegram_recipients','material_publications','homework_reports'
  ] loop
    execute format('drop trigger if exists %I on public.%I', table_name || '_set_updated_at', table_name);
    execute format('create trigger %I before update on public.%I for each row execute function public.set_updated_at()', table_name || '_set_updated_at', table_name);
  end loop;
end;
$$;

drop trigger if exists homework_progress_protect_submitted on public.homework_progress;
create trigger homework_progress_protect_submitted
before update on public.homework_progress
for each row execute function public.protect_submitted_homework();

-- RLS and browser privileges.
alter table public.homework_progress enable row level security;
alter table public.vocabulary_progress enable row level security;
alter table public.vocabulary_topic_progress enable row level security;
alter table public.grammar_progress enable row level security;
alter table public.telegram_recipients enable row level security;
alter table public.material_publications enable row level security;
alter table public.homework_reports enable row level security;

revoke all on table public.homework_progress, public.vocabulary_progress, public.vocabulary_topic_progress, public.grammar_progress from anon, authenticated;
grant select, insert, update on table public.homework_progress to anon;
grant select, insert, update, delete on table public.vocabulary_progress, public.vocabulary_topic_progress, public.grammar_progress to anon;
grant usage, select on all sequences in schema public to anon;
grant execute on function public.apply_vocabulary_test(text,text,jsonb,jsonb) to anon;

-- No public access to server-only Telegram tables.
revoke all on table public.telegram_recipients, public.material_publications, public.homework_reports from anon, authenticated;
grant all on table public.telegram_recipients, public.material_publications, public.homework_reports to service_role;
grant all on table public.homework_progress, public.vocabulary_progress, public.vocabulary_topic_progress, public.grammar_progress to service_role;
grant usage, select on all sequences in schema public to service_role;

drop policy if exists homework_select_amir on public.homework_progress;
drop policy if exists homework_insert_amir on public.homework_progress;
drop policy if exists homework_update_amir on public.homework_progress;
create policy homework_select_amir on public.homework_progress for select to anon using (student_id = 'amir');
create policy homework_insert_amir on public.homework_progress for insert to anon with check (student_id = 'amir');
create policy homework_update_amir on public.homework_progress for update to anon using (student_id = 'amir') with check (student_id = 'amir');

drop policy if exists vocabulary_select_amir on public.vocabulary_progress;
drop policy if exists vocabulary_insert_amir on public.vocabulary_progress;
drop policy if exists vocabulary_update_amir on public.vocabulary_progress;
drop policy if exists vocabulary_delete_amir on public.vocabulary_progress;
create policy vocabulary_select_amir on public.vocabulary_progress for select to anon using (student_id = 'amir');
create policy vocabulary_insert_amir on public.vocabulary_progress for insert to anon with check (student_id = 'amir');
create policy vocabulary_update_amir on public.vocabulary_progress for update to anon using (student_id = 'amir') with check (student_id = 'amir');
create policy vocabulary_delete_amir on public.vocabulary_progress for delete to anon using (student_id = 'amir');

drop policy if exists vocabulary_topic_select_amir on public.vocabulary_topic_progress;
drop policy if exists vocabulary_topic_insert_amir on public.vocabulary_topic_progress;
drop policy if exists vocabulary_topic_update_amir on public.vocabulary_topic_progress;
drop policy if exists vocabulary_topic_delete_amir on public.vocabulary_topic_progress;
create policy vocabulary_topic_select_amir on public.vocabulary_topic_progress for select to anon using (student_id = 'amir');
create policy vocabulary_topic_insert_amir on public.vocabulary_topic_progress for insert to anon with check (student_id = 'amir');
create policy vocabulary_topic_update_amir on public.vocabulary_topic_progress for update to anon using (student_id = 'amir') with check (student_id = 'amir');
create policy vocabulary_topic_delete_amir on public.vocabulary_topic_progress for delete to anon using (student_id = 'amir');

drop policy if exists grammar_select_amir on public.grammar_progress;
drop policy if exists grammar_insert_amir on public.grammar_progress;
drop policy if exists grammar_update_amir on public.grammar_progress;
drop policy if exists grammar_delete_amir on public.grammar_progress;
create policy grammar_select_amir on public.grammar_progress for select to anon using (student_id = 'amir');
create policy grammar_insert_amir on public.grammar_progress for insert to anon with check (student_id = 'amir');
create policy grammar_update_amir on public.grammar_progress for update to anon using (student_id = 'amir') with check (student_id = 'amir');
create policy grammar_delete_amir on public.grammar_progress for delete to anon using (student_id = 'amir');

-- Server-only tables intentionally have no public policies.
